-- 删除旧的sys_article表并重新创建
DROP TABLE IF EXISTS `sys_article`;

CREATE TABLE `sys_article` (
    `id` INT PRIMARY KEY,
    `article_title` VARCHAR(500) NOT NULL,
    `article_weight` INT DEFAULT 0,
    `small_picture` VARCHAR(255) DEFAULT NULL,
    `create_username` VARCHAR(100) DEFAULT NULL,
    `create_userid` VARCHAR(100) DEFAULT NULL,
    `create_time` DATETIME DEFAULT NULL,
    `update_time` DATETIME DEFAULT NULL,
    `publish_time` DATETIME DEFAULT NULL,
    `status` VARCHAR(10) DEFAULT NULL,
    `article_author` VARCHAR(100) DEFAULT NULL,
    `article_source` VARCHAR(255) DEFAULT NULL,
    `charge_editor` VARCHAR(100) DEFAULT NULL,
    `article_type` VARCHAR(100) DEFAULT NULL,
    `has_video` TINYINT DEFAULT 0,
    `put_on_top` TINYINT DEFAULT 0,
    `home_carousel` TINYINT DEFAULT 0,
    `make_headlines` TINYINT DEFAULT 0,
    `article_content` LONGTEXT DEFAULT NULL,
    `column_value` VARCHAR(100) DEFAULT NULL,
    `view_num` INT DEFAULT 0,
    `file_path` TEXT DEFAULT NULL,
    `abstract_text` TEXT DEFAULT NULL,
    `tenders_id` VARCHAR(100) DEFAULT NULL,
    `pro_id` VARCHAR(100) DEFAULT NULL,
    `is_gszd` TINYINT DEFAULT 0,
    `tenders_rule_history_id` VARCHAR(100) DEFAULT NULL,
    `village_code` VARCHAR(100) DEFAULT NULL,
    `pro_type` VARCHAR(100) DEFAULT NULL,
    `area` DECIMAL(15,2) DEFAULT NULL,
    `amount` DECIMAL(15,2) DEFAULT NULL,
    `pro_code` VARCHAR(100) DEFAULT NULL,
    `village_name` VARCHAR(255) DEFAULT NULL,
    `transfer_mode` VARCHAR(100) DEFAULT NULL,
    `tenders_code` VARCHAR(100) DEFAULT NULL,
    `dept_code` VARCHAR(100) DEFAULT NULL,
    `dept_name` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统文章表'; 